version: '3'
services:
  web:
    container_name: web_mytools
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  api:
    container_name: api_mytools
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./api:/api
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    container_name: nginx_mytools
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./app/static:/static
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:latest
    container_name: db_mytools
    restart: unless-stopped
    environment:
      POSTGRES_USER: mytools
      POSTGRES_PASSWORD: mytools
      POSTGRES_DB: mytools
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
