version: '3'
services:
  web:
    container_name: web_mytools
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

  api:
    container_name: api_mytools
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./api:/api

  nginx:
    image: nginx:latest
    container_name: nginx_mytools
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    command: sh -c "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj '/C=BR/ST=PB/L=Joao Pessoa/O=Jotinha/CN=localhost' && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443